version: '3'

networks:
  dev_net:
    driver: bridge

services:
  db:
    image: mariadb:latest
    container_name: mariadb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'tK421931.'
      MYSQL_DATABASE: 'techwars'
      MYSQL_USER: 'lucee'      
      MYSQL_PASSWORD: 'lemLrv931.'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'    
      # Where our data will be persisted
    volumes:
      - /home/dboehm/gitrepo/lucee_dev/database:/var/lib/mysql
    networks:
      - dev_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_dev
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY:     
      PMA_USER: 'lucee'
      PMA_PASSWORD: 'lemLrv931.'
    restart: always
    ports:
      - 8081:80
    networks:
      - dev_net

  lucee:
    image: lucee/lucee:5.3-nginx
    container_name: lucee_dev
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - /home/dboehm/gitrepo/TechWars:/var/www/
      - './password.txt:/opt/lucee/server/lucee-server/context/password.txt'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: 'techwars'
      DB_USER: 'lucee'
      DB_PASS: 'lemLrv931.'
    networks:
      - dev_net
