version: '3'

networks:
  my-network:
    driver: bridge

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - my-network

  lucee:
    image: lucee/lucee:latest
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - ./lucee-web:/var/www/lucee
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASS: mypassword
    networks:
      - my-network
